### ISSUE TITLE
How to prepare for breakage in piston-event_loop

### ISSUE THREAD

**Issue by bvssvni** [indiv0/tcod_window#2]
See https://github.com/PistonDevelopers/event_loop/issues/54

piston-event_loop will go through a redesign. Add the following:

``` Rust
use quack::Associative;

impl Associative for (PollEvent, TcodWindow) {
    type Type = Input;
}
```

**Comment by indiv0** [comment]
@bvssvni thanks for the heads up. I'll implement it once I have a bit of free time.
